name: Build APK
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
          channel: 'stable'

      - name: Build Project
        run: |
          flutter config --no-analytics
          flutter create .
          
          # Inject permissions into AndroidManifest.xml
          sed -i '/<\/manifest>/i \
          <uses-permission android:name="android.permission.INTERNET" />\
          <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />\
          <uses-permission android:name="android.permission.CHANGE_WIFI_STATE" />\
          <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />\
          <uses-permission android:name="android.permission.NEARBY_WIFI_DEVICES" />' android/app/src/main/AndroidManifest.xml
          
          flutter pub get
          flutter build apk --release --quiet

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
